name: Android APK Build

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch torchvision pillow
    
    - name: Export and quantize model
      run: |
        python3 scripts/export_model.py --formats torchscript onnx
        python3 scripts/quantize_model.py --input models/model/model_mobile.pt --verify
    
    - name: Copy assets to Android app
      run: |
        mkdir -p mobile/android/app/src/main/assets/models
        cp models/model/model_mobile_quant.pt mobile/android/app/src/main/assets/models/ 2>/dev/null || true
        cp models/model/model_mobile.onnx mobile/android/app/src/main/assets/models/ 2>/dev/null || true
        cp demo/test_screen.png mobile/android/app/src/main/assets/ 2>/dev/null || true
    
    - name: Grant execute permission for gradlew
      run: |
        cd mobile/android
        chmod +x gradlew
    
    - name: Build debug APK
      run: |
        cd mobile/android
        ./gradlew assembleDebug --stacktrace
      env:
        JAVA_TOOL_OPTIONS: -Xmx2048m
    
    - name: List build outputs
      run: |
        find mobile/android/app/build/outputs -name "*.apk"
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: autorl-arm-debug-apk
        path: mobile/android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
    
    - name: Get APK info
      run: |
        APK_PATH="mobile/android/app/build/outputs/apk/debug/app-debug.apk"
        if [ -f "$APK_PATH" ]; then
          echo "✅ APK built successfully"
          ls -lh "$APK_PATH"
          echo "Size: $(du -h $APK_PATH | cut -f1)"
        else
          echo "❌ APK not found"
          exit 1
        fi
    
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: mobile/android/app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
